### ISSUE TITLE
[question] how to list custom_attributes for vm?

### ISSUE THREAD

**Issue by DefinitelyNothingInteresting** [vmware/vsphere-automation-sdk-python#385]
### Is your feature request related to a problem? Please describe.

I'm looking for a way to retrieve and edit custom attributes for a given VM. I can't find it now. Is it even possible?

### Describe the solution you'd like

 custom_attributes could be added to vsphere_client.vcenter.vm or  vsphere_client.vcenter.vm.guest

**Comment by mtsvetanov** [comment]
You can't do this with the vsphere-automation-sdk-for-python. You need to use the [vSphere Web Services AP](https://developer.vmware.com/apis/1355/vsphere)I for example using [pyvmomi  ](https://github.com/vmware/pyvmomi)

Or using the [VI/JSON API](https://developer.vmware.com/apis/vi-json/latest/) by crafting the HTTP/REST request, but this is only available since 8.0 Update 1.
