### ISSUE TITLE
Could not find a version that satisfies the requirement vmc-client-bindings (from -r requirements.txt (line 6)) (from versions: )

### ISSUE THREAD

**Issue by ShridharSChini** [vmware/vsphere-automation-sdk-python#46]
![git2](https://user-images.githubusercontent.com/34676240/36849147-425f57a8-1d89-11e8-9f02-72ac98640a76.png)

**Comment by tianhao64** [comment]
@ShridharSChini Are you using the latest version? What's the content of your requirements.txt?

**Comment by sssharanster** [comment]
Try something like this:
pip install --upgrade --force-reinstall -r requirements.txt --extra-index-url file://$PWD/lib

**Comment by ShridharSChini** [comment]
hi sir/madam,

  Tanks for replying .. its working


Regards
shridhar.

**Comment by kandadeepak** [comment]
Hi,

I was trying to install the get the similar error message,and run the command suggested by @sssharanster but still i can see the error message while installing. 

[install.txt](https://github.com/vmware/vsphere-automation-sdk-python/files/1799708/install.txt)

root@ubuntu:/tmp/vsphere-automation-sdk-python-master# python -V
Python 3.6.3

root@ubuntu:/tmp/vsphere-automation-sdk-python-master# lsb_release -a
No LSB modules are available.
Distributor ID: Ubuntu
Description:    Ubuntu 17.10
Release:        17.10
Codename:       artful

**Comment by tianhao64** [comment]
Are you using a virtualenv? Can you try to do:
pip install wheel

**Comment by kandadeepak** [comment]
Yes for virtual en 15.1.0,Wheel already installed in this box.

Deepak.K

Please excuse typos.

Sent from Nokia

On 12-Mar-2018 11:38 PM, "Tianhao He" <notifications@github.com> wrote:

Are you using a virtualenv? Can you try to do:
pip install wheel

—
You are receiving this because you commented.
Reply to this email directly, view it on GitHub
<https://github.com/vmware/vsphere-automation-sdk-python/issues/46#issuecomment-372408837>,
or mute the thread

**Comment by tianhao64** [comment]
See this error in your log:
Running setup.py bdist_wheel for suds-jurko: started
  Running setup.py bdist_wheel for suds-jurko: finished with status 'error'
Looks like wheel was not successfully installed.
