### ISSUE TITLE
New API for license manager 

### ISSUE THREAD

**Issue by Saamy88** [vmware/vsphere-automation-sdk-python#53]
Hello, 

I am currently using license Manager using the pyvmomi library on my python code and I am using the following methods: UpdateAssignedLicense() and QueryAssignedLicenses(). According to the following link: https://www.vmware.com/support/developer/converter-sdk/conv60_apireference/vim.LicenseAssignmentManager.html 

These methods are deprecated and it wants me to `use cis.license.management.SystemManagementService`. I want to use the new APIs but I dont how to call them from pyvmomi. Documentation online does not help. Any ideas on how to use these new APIs?

**Comment by morrykatz** [comment]
The APIs in https://www.vmware.com/support/developer/converter-sdk/conv60_apireference/vim.LicenseAssignmentManager.html were incorrectly documented as having been deprecated in vSphere API 6.0.  These APIs continue to function as documented in vSphere 6.x.   A correction to the documentation is in process.

Furthermore, there are no new licensing methods in cis.license.management.SystemManagementService, which is why you were unable to find any documentation for them.

I apologize for any inconvenience this error in our documentation has caused you.

Morry Katz
VMware Product Manager
Licensing Solutions

**Comment by tianhao64** [comment]
Thanks @morrykatz. Closing this issue.

**Comment by udautkarsh** [comment]
I had the same confusion after I implemented those functions until I came here.  I can still see method UpdateAssignedLicense() and QueryAssignedLicenses() etc in pyvmomi 7.0.1
